# Generated by Django 4.2.4 on 2023-10-25 15:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionAvancee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extension',
            name='telephone_1',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Veuillez entrer un numéro de téléphone valide', regex='[0-9]{9}')], verbose_name='Téléphone'),
        ),
    ]
