# Generated by Django 4.2 on 2023-05-01 18:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], max_length=20, verbose_name='Sexe')),
                ('email', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Veuillez entrer un numéro de téléphone valide', regex='[0-9]{9}')])),
                ('adresse', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('date_arrivee', models.DateField(blank=True, null=True, verbose_name="Date d'arrivée à CMLN")),
                ('emplacement', models.CharField(choices=[('MEMBRE', 'Membre'), ('INTEGRATION', "En cours d'intégration"), ('EN_FORMATION', 'En cours de formation'), ('AERD', 'AERD')], max_length=20, verbose_name='Situation actuelle')),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('inactif', models.BooleanField(default=False, verbose_name="Desactivé(Ne cocher que si vous ne souhaiter plus gérer cette personne dans l'application)")),
                ('commentaire', models.CharField(blank=True, max_length=2000)),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.extension')),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Veuillez entrer un numéro de téléphone valide', regex='[0-9]{9}')])),
                ('date_inscription', models.DateField(auto_now_add=True, null=True, verbose_name="Date d'inscription")),
                ('commentaire', models.CharField(blank=True, max_length=500)),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.extension')),
            ],
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
        migrations.AddField(
            model_name='aerd',
            name='formateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cmlnGestion.membre', verbose_name="Formateur (A remplir uniquement si 'en cours de formation')"),
        ),
    ]
