# Generated by Django 4.2 on 2023-05-02 08:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0002_aerd_membre_delete_personne_aerd_formateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('ministere', models.CharField(blank=True, choices=[('PUISSANCE', 'Puissance'), ('LOUANGE', 'Louange'), ('JEUNESSE', 'CMLN Etoile'), ('ENFANTS', 'CMLN Junior'), ('AMENAGEMENT', 'Aménagement')], max_length=100, null=True, verbose_name='Ministère')),
            ],
        ),
        migrations.RemoveField(
            model_name='aerd',
            name='date_inscription',
        ),
        migrations.RemoveField(
            model_name='aerd',
            name='emplacement',
        ),
        migrations.RemoveField(
            model_name='aerd',
            name='formateur',
        ),
        migrations.AddField(
            model_name='aerd',
            name='date_bapteme',
            field=models.DateField(blank=True, null=True, verbose_name='Date de bapteme(par immersion)'),
        ),
        migrations.AddField(
            model_name='aerd',
            name='situation',
            field=models.CharField(blank=True, choices=[('MEMBRE', 'Membre'), ('INTEGRATION', "En cours d'intégration - N1"), ('STAGIAIRE', 'STAGIAIRE'), ('AERD', 'Aerd confirmé'), ('FORMATION', 'En formation N+')], max_length=100, null=True, verbose_name='Situation actuelle'),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='adresse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='commentaire',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='date_arrivee',
            field=models.DateField(auto_now_add=True, null=True, verbose_name="Date d'arrivée à CMLN"),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='inactif',
            field=models.BooleanField(default=False, verbose_name="Desactivé (Ne cocher que si vous ne souhaitez plus gérer ce AERD dans l'application)"),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='sexe',
            field=models.CharField(blank=True, choices=[('F', 'Féminin'), ('M', 'Masculin')], max_length=20, null=True, verbose_name='Sexe'),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Veuillez entrer un numéro de téléphone valide', regex='[0-9]{9}')]),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aerd',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cmlnGestion.departement'),
        ),
    ]
