# Generated by Django 4.2 on 2023-05-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0003_departement_remove_aerd_date_inscription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aerd',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='aerd',
            name='date_arrivee',
        ),
        migrations.RemoveField(
            model_name='aerd',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='aerd',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aerd',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='aerd',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='aerd',
            name='sexe',
        ),
        migrations.RemoveField(
            model_name='aerd',
            name='telephone',
        ),
        migrations.AddField(
            model_name='aerd',
            name='membre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cmlnGestion.membre'),
        ),
        migrations.AddField(
            model_name='aerd',
            name='niveau_formation',
            field=models.CharField(blank=True, choices=[('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4')], max_length=100, null=True, verbose_name='Niveau actuelle(si AERD confirmé ou en formation N+)'),
        ),
        migrations.AddField(
            model_name='aerd',
            name='position',
            field=models.CharField(blank=True, choices=[('LEADER', 'Leader Principal'), ('PASTEUR', 'Pasteur titulaire'), ('PASTEUR_ADJOINT', 'Pasteur Stagiaire'), ('AP', 'Assistant Pasteur'), ('ANCIEN', 'Ancien'), ('DIACRE', 'Diacre')], max_length=100, null=True, verbose_name='Position actuelle'),
        ),
        migrations.AddField(
            model_name='membre',
            name='baptise',
            field=models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=20, null=True, verbose_name='Baptisé'),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_arrivee',
            field=models.DateField(auto_now_add=True, null=True, verbose_name="Date d'arrivée à CMLN"),
        ),
        migrations.AddField(
            model_name='membre',
            name='sexe',
            field=models.CharField(blank=True, choices=[('F', 'Féminin'), ('M', 'Masculin')], max_length=20, null=True, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='membre',
            name='situation',
            field=models.CharField(blank=True, choices=[('NOUVEAU', 'Nouvel arrivant'), ('INTEGRATION', "En cours d'intégration - N1")], max_length=100, null=True, verbose_name='Situation actuelle'),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='commentaire',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='situation',
            field=models.CharField(blank=True, choices=[('STAGIAIRE', 'STAGIAIRE'), ('AERD', 'Aerd confirmé'), ('FORMATION', 'En formation N+')], max_length=100, null=True, verbose_name='Situation actuelle'),
        ),
    ]
