# Generated by Django 4.2 on 2023-05-11 15:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0009_remove_coordonateur_departement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AerdMinistere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='ouvrier',
            name='aerd',
        ),
        migrations.RenameField(
            model_name='membre',
            old_name='telephone',
            new_name='telephone_1',
        ),
        migrations.RemoveField(
            model_name='ancien',
            name='aerd',
        ),
        migrations.RemoveField(
            model_name='assistantpasteur',
            name='aerd',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='coordonateur',
        ),
        migrations.RemoveField(
            model_name='departement',
            name='ministere',
        ),
        migrations.RemoveField(
            model_name='diacre',
            name='aerd',
        ),
        migrations.RemoveField(
            model_name='leader',
            name='aerd',
        ),
        migrations.RemoveField(
            model_name='ministre',
            name='aerd',
        ),
        migrations.RemoveField(
            model_name='pasteur',
            name='aerd',
        ),
        migrations.AddField(
            model_name='aerd',
            name='departement',
            field=models.ManyToManyField(to='cmlnGestion.departement'),
        ),
        migrations.AddField(
            model_name='ancien',
            name='coordonateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.coordonateur', verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='assistantpasteur',
            name='coordonateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.coordonateur', verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='diacre',
            name='charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.charge', verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='leader',
            name='pasteur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.pasteur', verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='membre',
            name='etat_civil',
            field=models.CharField(blank=True, choices=[('Célibataire', 'Célibataire'), ('Marié(e)', 'Marié(e)'), ('Divorcé(e)', 'Divorcé(e)'), ('Veuf(ve)', 'Veuf(ve)')], max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='membre',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Veuillez entrer un numéro de téléphone valide', regex='[0-9]{9}')]),
        ),
        migrations.AddField(
            model_name='ministere',
            name='departement',
            field=models.ManyToManyField(to='cmlnGestion.departement', verbose_name='Departement'),
        ),
        migrations.AddField(
            model_name='ministre',
            name='coordonateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.coordonateur', verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='pasteur',
            name='ministre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.ministre', verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='commentaire',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.extension', verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='membre',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='cmlnGestion.membre', verbose_name='Ouvrier'),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='commentaire',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.extension', verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='assistantpasteur',
            name='commentaire',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='assistantpasteur',
            name='extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.extension', verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='aerd',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.aerd', verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='coordonateur',
            name='aerd',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.aerd', verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='coordonateur',
            name='commentaire',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='diacre',
            name='commentaire',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='diacre',
            name='extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.extension', verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='commentaire',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='extension',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.extension', verbose_name='Extension'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='baptise',
            field=models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], max_length=100, null=True, verbose_name='Baptisé'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='commentaire',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='ministre',
            name='commentaire',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Commentaires'),
        ),
        migrations.AlterField(
            model_name='pasteur',
            name='commentaire',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Commentaires'),
        ),
        migrations.AlterUniqueTogether(
            name='membre',
            unique_together={('prenom', 'nom')},
        ),
        migrations.DeleteModel(
            name='AerdDepartement',
        ),
        migrations.DeleteModel(
            name='Ouvrier',
        ),
        migrations.AddField(
            model_name='aerdministere',
            name='aerd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.aerd', verbose_name='Ouvrier'),
        ),
        migrations.AddField(
            model_name='aerdministere',
            name='ministere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.ministere', verbose_name='Departement'),
        ),
    ]
