# Generated by Django 4.2 on 2023-05-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0010_aerdministere_remove_ouvrier_aerd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerd',
            name='niveau_formation',
            field=models.CharField(blank=True, choices=[('N_A', '-'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4')], max_length=100, null=True, verbose_name='Niveau actuelle(si AERD confirmé ou en formation N+)'),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='position',
            field=models.CharField(blank=True, choices=[('LEADER', 'Leader Principal'), ('PASTEUR', 'Pasteur titulaire'), ('PASTEUR_ADJOINT', 'Pasteur Stagiaire'), ('AP', 'Assistant Pasteur'), ('ANCIEN', 'Ancien(ne)'), ('DIACRE', 'Diacre/ Diaconnesse')], max_length=100, null=True, verbose_name='Position actuelle'),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='situation',
            field=models.CharField(blank=True, choices=[('STAGIAIRE', 'Stagiaire'), ('AERD', 'Aerd confirmé'), ('FORMATION_N', 'En formation N+')], max_length=100, null=True, verbose_name='Situation actuelle'),
        ),
    ]
