# Generated by Django 4.2 on 2023-05-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0012_alter_aerd_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerd',
            name='situation',
            field=models.CharField(blank=True, choices=[('NA', '-'), ('STAGIAIRE', 'Stagiaire'), ('AERD', 'Aerd confirmé'), ('FORMATION_N', 'En formation N+')], max_length=100, null=True, verbose_name='Situation actuelle'),
        ),
    ]
