# Generated by Django 4.2.1 on 2023-05-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0014_activite'),
    ]

    operations = [
        migrations.AddField(
            model_name='activite',
            name='nouveaux_venus',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
