# Generated by Django 4.2.1 on 2023-06-15 10:35

import cmlnGestion.models.model_membre
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0019_alter_activite_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='profile_image',
            field=models.ImageField(blank=True, default=cmlnGestion.models.model_membre.get_default_profile_image, max_length=255, null=True, upload_to=cmlnGestion.models.model_membre.get_profile_image_filepath),
        ),
    ]
