# Generated by Django 4.2.1 on 2023-06-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0020_membre_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='commentaire',
            field=models.CharField(blank=True, default='RAS', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='situation',
            field=models.CharField(blank=True, choices=[('NOUVEAU', 'Nouvel arrivant'), ('INTEGRATION', "En cours d'intégration - N1"), ('AERD', 'Aerd')], max_length=100, null=True, verbose_name='Situation actuelle'),
        ),
    ]
