# Generated by Django 4.2.1 on 2023-06-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0021_alter_membre_commentaire_alter_membre_situation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='commentaire',
            field=models.CharField(default='RAS', max_length=500),
        ),
    ]
