# Generated by Django 4.2.1 on 2023-06-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0022_alter_membre_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_arrivee',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name="Date d'arrivée à CMLN"),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_bapteme',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Date de bapteme(par immersion)'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_naissance',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
