# Generated by Django 4.2.1 on 2023-06-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0023_alter_membre_date_arrivee_alter_membre_date_bapteme_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_arrivee',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'arrivée à CMLN"),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_bapteme',
            field=models.DateField(blank=True, null=True, verbose_name='Date de bapteme(par immersion)'),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
