# Generated by Django 4.2.1 on 2023-06-20 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0024_alter_membre_date_arrivee_alter_membre_date_bapteme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pasteur',
            name='ministre',
        ),
        migrations.AddField(
            model_name='pasteur',
            name='ancien',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.ancien', verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='ministere',
            name='ministre',
            field=models.CharField(choices=[('', ''), ('SOGNHY PAKA', 'SOGNHY PAKA'), ('Chistelle PAKA', 'Christelle')], default='-', max_length=100, verbose_name='Situation actuelle'),
        ),
        migrations.DeleteModel(
            name='Ministre',
        ),
    ]
