# Generated by Django 4.2.1 on 2023-06-20 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0025_remove_pasteur_ministre_pasteur_ancien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerd',
            name='ministere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.ministere', verbose_name='Ministère'),
        ),
    ]
