# Generated by Django 4.2.1 on 2023-06-20 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0026_aerd_ministere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aerd',
            name='departement',
        ),
        migrations.AlterField(
            model_name='ministere',
            name='ministre',
            field=models.CharField(choices=[('Non défini', '---Non défini---'), ('SOGNHY PAKA', 'SOGNHY PAKA'), ('Chistelle PAKA', 'Christelle')], default='-', max_length=100, verbose_name='Ministre'),
        ),
        migrations.AddField(
            model_name='aerd',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.departement'),
        ),
    ]
