# Generated by Django 4.2.1 on 2023-06-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0027_remove_aerd_departement_alter_ministere_ministre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aerd',
            name='departement',
        ),
        migrations.AddField(
            model_name='aerd',
            name='departement',
            field=models.ManyToManyField(to='cmlnGestion.departement'),
        ),
    ]
