# Generated by Django 4.2.1 on 2023-06-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0028_remove_aerd_departement_aerd_departement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aerd',
            name='ministere',
        ),
        migrations.RemoveField(
            model_name='pasteur',
            name='ancien',
        ),
        migrations.AlterField(
            model_name='ministere',
            name='ministre',
            field=models.CharField(choices=[('', ''), ('SOGNHY PAKA', 'SOGNHY PAKA'), ('Chistelle PAKA', 'Christelle')], default='-', max_length=100, verbose_name='Situation actuelle'),
        ),
        migrations.CreateModel(
            name='Ministre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(blank=True, null=True, verbose_name='Prise de fonction')),
                ('date_sortie', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fin de fonction')),
                ('inactif', models.BooleanField(default=False, verbose_name='Desactivé')),
                ('commentaire', models.TextField(blank=True, max_length=500, null=True, verbose_name='Commentaires')),
                ('coordonateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.coordonateur', verbose_name='Nom')),
            ],
        ),
        migrations.AddField(
            model_name='pasteur',
            name='ministre',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.ministre', verbose_name='Nom'),
        ),
    ]
