# Generated by Django 4.2.4 on 2023-10-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0030_alter_ministere_ministre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activite',
        ),
    ]
