# Generated by Django 4.2.4 on 2023-10-25 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0032_alter_aerd_extension_alter_ancien_extension_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aerd',
            name='departement',
        ),
        migrations.AddField(
            model_name='aerd',
            name='ministere_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aerds', to='cmlnGestion.ministere', verbose_name='Ministère principal'),
        ),
        migrations.AddField(
            model_name='aerd',
            name='ministere_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmlnGestion.ministere', verbose_name='Ministère secondaire'),
        ),
    ]
