# Generated by Django 4.2.4 on 2023-10-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0033_remove_aerd_departement_aerd_ministere_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='baptise',
            field=models.CharField(blank=True, choices=[('OUI', 'OUI'), ('NON', 'NON')], default='-', max_length=100, null=True, verbose_name='Baptisé'),
        ),
    ]
