# Generated by Django 4.2.4 on 2023-10-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmlnGestion', '0034_alter_membre_baptise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='baptise',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], default='-', max_length=100, verbose_name='Baptisé'),
        ),
    ]
