# Generated by Django 4.2.1 on 2023-05-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='staff',
        ),
    ]
