# Generated by Django 4.2 on 2023-05-01 10:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name="Date d'ajout")),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de mise à jour')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=150)),
                ('pays', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('email', models.CharField(max_length=150)),
                ('adresse', models.CharField(max_length=100)),
                ('ville', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Veuillez entrer un numéro de téléphone valide', regex='[0-9]{9}')])),
                ('date_inscription', models.DateField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('commentaire', models.CharField(blank=True, max_length=100)),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.extension')),
            ],
        ),
    ]
