# Generated by Django 4.2 on 2023-05-02 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmln', '0004_remove_aerd_adresse_remove_aerd_date_arrivee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aerd',
            name='membre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cmln.membre', verbose_name='Ouvrier'),
        ),
    ]
