# Generated by Django 4.2 on 2023-05-04 13:01

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cmln', '0005_alter_aerd_membre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Bref description')),
            ],
        ),
        migrations.RenameField(
            model_name='departement',
            old_name='nom',
            new_name='designation',
        ),
        migrations.RemoveField(
            model_name='aerd',
            name='date_bapteme',
        ),
        migrations.RemoveField(
            model_name='aerd',
            name='ville',
        ),
        migrations.AddField(
            model_name='aerd',
            name='responsabilite',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='departement',
            name='attributions',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Attributions'),
        ),
        migrations.AddField(
            model_name='membre',
            name='date_bapteme',
            field=models.DateField(blank=True, null=True, verbose_name='Date de bapteme(par immersion)'),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.departement', verbose_name='Departement'),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='membre',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.membre', verbose_name='Ouvrier'),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='position',
            field=models.CharField(blank=True, choices=[('Leader Principal', 'Leader Principal'), ('Pasteur titulaire', 'Pasteur titulaire'), ('Pasteur Stagiaire', 'Pasteur Stagiaire'), ('Assistant Pasteur', 'Assistant Pasteur'), ('Ancien(ne)', 'Ancien(ne)'), ('Diacre/ Diaconnesse', 'Diacre/ Diaconnesse'), ('Ouvrier', 'Ouvrier')], max_length=100, null=True, verbose_name='Position actuelle'),
        ),
        migrations.AlterField(
            model_name='aerd',
            name='situation',
            field=models.CharField(blank=True, choices=[('-', '-'), ('Stagiaire', 'Stagiaire'), ('Aerd confirmé', 'Aerd confirmé'), ('En formation N+', 'En formation N+')], max_length=100, null=True, verbose_name='Situation actuelle'),
        ),
        migrations.AlterField(
            model_name='extension',
            name='pays',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='extension',
            name='ville',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='commentaire',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='membre',
            name='date_arrivee',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'arrivée à CMLN"),
        ),
        migrations.CreateModel(
            name='Pasteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Prise de fonction')),
                ('date_sortie', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fin de fonction')),
                ('inactif', models.BooleanField(default=False, verbose_name='Desactivé')),
                ('commentaire', models.TextField(blank=True, max_length=500, null=True)),
                ('aerd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.aerd', verbose_name='Nom')),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.extension')),
            ],
        ),
        migrations.CreateModel(
            name='Ouvrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Prise de fonction')),
                ('date_sortie', models.DateTimeField(blank=True, null=True, verbose_name='Fin de fonction')),
                ('inactif', models.BooleanField(default=False, verbose_name='Desactivé')),
                ('commentaire', models.TextField(blank=True, max_length=500, null=True)),
                ('aerd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.aerd', verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Ministre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Prise de fonction')),
                ('date_sortie', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fin de fonction')),
                ('inactif', models.BooleanField(default=False, verbose_name='Desactivé')),
                ('commentaire', models.TextField(blank=True, max_length=500, null=True)),
                ('aerd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.aerd', verbose_name='Nom')),
                ('ministere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.ministere', verbose_name='Ministère')),
            ],
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal', models.BooleanField(default=False, verbose_name='Leader Principal')),
                ('communaute', models.CharField(blank=True, choices=[('Communauté CMLN/ Ensemble des églises CMLN', 'Communauté CMLN/ Ensemble des églises CMLN'), ('-', '-')], max_length=120, null=True, verbose_name='Communauté')),
                ('date_entree', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Prise de fonction')),
                ('date_sortie', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fin de fonction')),
                ('inactif', models.BooleanField(default=False, verbose_name='Desactivé')),
                ('commentaire', models.TextField(blank=True, max_length=500, null=True)),
                ('aerd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.aerd', verbose_name='Nom')),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.extension')),
            ],
        ),
        migrations.CreateModel(
            name='Diacre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Prise de fonction')),
                ('date_sortie', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fin de fonction')),
                ('inactif', models.BooleanField(default=False, verbose_name='Desactivé')),
                ('commentaire', models.TextField(blank=True, max_length=500, null=True)),
                ('aerd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.aerd', verbose_name='Nom')),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.extension')),
            ],
        ),
        migrations.CreateModel(
            name='Coordonateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Prise de fonction')),
                ('date_sortie', models.DateTimeField(blank=True, null=True, verbose_name='Fin de fonction')),
                ('inactif', models.BooleanField(default=False, verbose_name='Desactivé')),
                ('commentaire', models.TextField(blank=True, max_length=500, null=True)),
                ('aerd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.aerd', verbose_name='Nom')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Prise de fonction')),
                ('date_sortie', models.DateTimeField(blank=True, null=True, verbose_name='Fin de fonction')),
                ('inactif', models.BooleanField(default=False, verbose_name='Desactivé')),
                ('commentaire', models.TextField(blank=True, max_length=500, null=True)),
                ('aerd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.aerd', verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='AssistantPasteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stagiaire', models.BooleanField(default=False, verbose_name='Adjoint')),
                ('date_entree', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Prise de fonction')),
                ('date_sortie', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fin de fonction')),
                ('inactif', models.BooleanField(default=False, verbose_name='Desactivé')),
                ('commentaire', models.TextField(blank=True, max_length=500, null=True)),
                ('aerd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.aerd', verbose_name='Nom')),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.extension')),
                ('pasteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.pasteur')),
            ],
        ),
        migrations.CreateModel(
            name='Ancien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entree', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Prise de fonction')),
                ('date_sortie', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fin de fonction')),
                ('inactif', models.BooleanField(default=False, verbose_name='Desactivé')),
                ('commentaire', models.TextField(blank=True, max_length=500, null=True)),
                ('aerd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.aerd', verbose_name='Nom')),
                ('extension', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.extension')),
            ],
        ),
        migrations.AddField(
            model_name='aerd',
            name='ministere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.ministere', verbose_name='Ministère'),
        ),
        migrations.AlterField(
            model_name='departement',
            name='ministere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.ministere'),
        ),
    ]
