# Generated by Django 4.2 on 2023-05-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmln', '0006_ministere_rename_nom_departement_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ancien',
            name='date_entree',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prise de fonction'),
        ),
        migrations.AlterField(
            model_name='ancien',
            name='date_sortie',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de fonction'),
        ),
        migrations.AlterField(
            model_name='assistantpasteur',
            name='date_entree',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prise de fonction'),
        ),
        migrations.AlterField(
            model_name='assistantpasteur',
            name='date_sortie',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de fonction'),
        ),
        migrations.AlterField(
            model_name='charge',
            name='date_entree',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prise de fonction'),
        ),
        migrations.AlterField(
            model_name='coordonateur',
            name='date_entree',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prise de fonction'),
        ),
        migrations.AlterField(
            model_name='diacre',
            name='date_entree',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prise de fonction'),
        ),
        migrations.AlterField(
            model_name='diacre',
            name='date_sortie',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de fonction'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='date_entree',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prise de fonction'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='date_sortie',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de fonction'),
        ),
        migrations.AlterField(
            model_name='ministre',
            name='date_entree',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prise de fonction'),
        ),
        migrations.AlterField(
            model_name='ouvrier',
            name='date_entree',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'entrée"),
        ),
        migrations.AlterField(
            model_name='pasteur',
            name='date_entree',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prise de fonction'),
        ),
        migrations.AlterField(
            model_name='pasteur',
            name='date_sortie',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin de fonction'),
        ),
    ]
