# Generated by Django 4.2 on 2023-05-04 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmln', '0007_alter_ancien_date_entree_alter_ancien_date_sortie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aerd',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='aerd',
            name='ministere',
        ),
        migrations.RemoveField(
            model_name='ministre',
            name='ministere',
        ),
        migrations.AddField(
            model_name='ministere',
            name='ministre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.ministre', verbose_name='Ministre'),
        ),
        migrations.CreateModel(
            name='AerdDepartement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aerd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.aerd', verbose_name='Ouvrier')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.departement', verbose_name='Departement')),
            ],
        ),
    ]
