# Generated by Django 4.2 on 2023-05-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmln', '0008_remove_aerd_departement_remove_aerd_ministere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordonateur',
            name='departement',
        ),
        migrations.AddField(
            model_name='departement',
            name='coordonateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmln.coordonateur', verbose_name='Coordonateur'),
        ),
    ]
